import React from "react";

export const styles: Record<string, React.CSSProperties> = {
    container: {
        display: "flex",
        flexDirection: "column",
        height: "100vh",
        backgroundColor: "#1e1e1e",
        color: "#e0e0e0",
        fontFamily: "'Segoe UI', Tahoma, Geneva, Verdana, sans-serif",
    },
    header: {
        display: "flex",
        alignItems: "center",
        justifyContent: "space-between",
        padding: "8px 16px",
        borderBottom: "1px solid #333",
        backgroundColor: "#252526",
        flexShrink: 0,
    },
    headerLeft: {
        display: "flex",
        alignItems: "center",
        gap: "12px",
    },
    headerRight: {
        display: "flex",
        alignItems: "center",
    },
    starButtonWrapper: {
        position: "relative" as const,
    },
    starButton: {
        display: "inline-flex",
        alignItems: "center",
        gap: "4px",
        padding: "4px 10px",
        backgroundColor: "#3c3c3c",
        border: "1px solid #555",
        borderRadius: "4px",
        color: "#e0e0e0",
        fontSize: "12px",
        textDecoration: "none",
        cursor: "pointer",
        transition: "background-color 0.15s",
    },
    tooltip: {
        position: "absolute" as const,
        top: "100%",
        right: 0,
        marginTop: "8px",
        padding: "10px 12px",
        backgroundColor: "#3c3c3c",
        border: "1px solid #555",
        borderRadius: "4px",
        boxShadow: "0 4px 12px rgba(0,0,0,0.3)",
        opacity: 0,
        visibility: "hidden" as const,
        transition: "opacity 0.15s, visibility 0.15s",
        zIndex: 100,
        minWidth: "140px",
    },
    tooltipTitle: {
        fontSize: "10px",
        fontWeight: 600,
        color: "#888",
        textTransform: "uppercase" as const,
        marginBottom: "6px",
        letterSpacing: "0.5px",
    },
    tooltipLink: {
        display: "block",
        padding: "4px 0",
        color: "#6cb6ff",
        fontSize: "12px",
        textDecoration: "none",
    },
    title: {
        margin: 0,
        fontSize: "16px",
        fontWeight: 500,
        color: "#fff",
    },
    status: {
        fontSize: "12px",
        color: "#888",
    },
    layoutContainer: {
        flex: 1,
        overflow: "hidden",
    },
    panelContainer: {
        display: "flex",
        flexDirection: "column",
        height: "100%",
        backgroundColor: "#1e1e1e",
        overflow: "hidden",
    },
    editorFill: {
        flex: 1,
        minHeight: 0,
    },
    statusBar: {
        padding: "4px 12px",
        backgroundColor: "#2d2d30",
        fontSize: "12px",
        color: "#888",
        borderBottom: "1px solid #333",
    },
    error: {
        padding: "8px 12px",
        backgroundColor: "#5a1d1d",
        color: "#f88",
        fontSize: "12px",
        borderTop: "1px solid #6b2d2d",
    },
    diffEditorContainer: {
        flex: 1,
        display: "flex",
        flexDirection: "column",
        minHeight: 0,
        overflow: "hidden",
    },
    sqlPreviewSection: {
        borderTop: "1px solid #333",
        backgroundColor: "#252526",
        maxHeight: "140px",
        overflow: "auto",
        flexShrink: 0,
    },
    sqlPreviewHeader: {
        display: "flex",
        alignItems: "center",
        justifyContent: "space-between",
        padding: "6px 10px",
        position: "sticky",
        top: 0,
        backgroundColor: "#252526",
        borderBottom: "1px solid #333",
        zIndex: 1,
    },
    sectionTitle: {
        fontSize: "11px",
        fontWeight: 500,
        color: "#999",
    },
    sqlPreview: {
        padding: "4px 10px 8px",
    },
    sqlStatement: {
        padding: "2px 0",
        fontFamily: "'Consolas', 'Courier New', monospace",
        fontSize: "11px",
        color: "#ce9178",
    },
    sqlParams: {
        color: "#6a9955",
    },
    placeholder: {
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        height: "100%",
        color: "#666",
        fontSize: "13px",
    },
    mermaidContainer: {
        display: "flex",
        flexDirection: "column",
        height: "100%",
        overflow: "hidden",
    },
    mermaidDiagram: {
        backgroundColor: "#252526",
        borderRadius: "4px",
        margin: "12px",
        padding: "12px",
        overflow: "auto",
        display: "flex",
        justifyContent: "center",
        flex: 1,
    },
    mermaidSource: {
        backgroundColor: "#252526",
        borderRadius: "4px",
        padding: "10px",
        flexShrink: 0,
    },
    mermaidSummary: {
        cursor: "pointer",
        fontSize: "11px",
        color: "#888",
    },
    mermaidCode: {
        margin: "10px 0 0",
        padding: "10px",
        backgroundColor: "#1e1e1e",
        borderRadius: "4px",
        fontSize: "11px",
        overflow: "auto",
        color: "#d4d4d4",
    },
    primaryButton: {
        padding: "4px 12px",
        backgroundColor: "#0078d4",
        border: "none",
        borderRadius: "3px",
        color: "#fff",
        fontSize: "11px",
        fontWeight: 500,
        cursor: "pointer",
    },
    toolbarRow: {
        display: "flex",
        alignItems: "center",
        gap: "8px",
        padding: "6px 10px",
        backgroundColor: "#252526",
        borderBottom: "1px solid #333",
        flexShrink: 0,
    },
    dropdown: {
        padding: "3px 8px",
        backgroundColor: "#3c3c3c",
        border: "1px solid #555",
        borderRadius: "3px",
        color: "#e0e0e0",
        fontSize: "12px",
        cursor: "pointer",
        outline: "none",
    },
    numberInput: {
        width: "60px",
        padding: "3px 8px",
        backgroundColor: "#3c3c3c",
        border: "1px solid #555",
        borderRadius: "3px",
        color: "#e0e0e0",
        fontSize: "12px",
        outline: "none",
    },
    toolbarLabel: {
        fontSize: "11px",
        color: "#999",
        marginLeft: "8px",
    },
    sectionDescription: {
        fontSize: "11px",
        color: "#888",
        fontStyle: "italic",
    },
    headerLeftGroup: {
        display: "flex",
        alignItems: "center",
        gap: "8px",
        flex: 1,
        minWidth: 0,
    },
    cliCommandBar: {
        display: "flex",
        alignItems: "center",
        justifyContent: "space-between",
        padding: "14px 10px 6px",
        backgroundColor: "#2d2d30",
        borderBottom: "1px solid #333",
        fontSize: "11px",
        flexShrink: 0,
        height: "40px",
        boxSizing: "border-box",
    },
    cliCode: {
        fontFamily: "'Consolas', 'Courier New', monospace",
        color: "#9cdcfe",
        backgroundColor: "#1e1e1e",
        padding: "2px 6px",
        borderRadius: "3px",
        fontSize: "11px",
    },
    resetButton: {
        padding: "3px 10px",
        backgroundColor: "#3c3c3c",
        border: "1px solid #555",
        borderRadius: "3px",
        color: "#fff",
        fontSize: "11px",
        cursor: "pointer",
    },
};
